package com.chenyue404.gboardhook

object StatusProtocol {
    const val ACTION_REQUEST = "com.lycidias93.gboardhookah.STATUS_REQUEST"
    const val ACTION_RESPONSE = "com.lycidias93.gboardhookah.STATUS_RESPONSE"
    const val ACTION_PUSH = "com.lycidias93.gboardhookah.STATUS_PUSH"
    const val PERMISSION_STATUS = "com.lycidias93.gboardhookah.permission.STATUS"

    const val PREF_TOKEN = "status_channel_token"
    const val PREF_SNAPSHOT_PRESENT = "runtime_status_snapshot_present"

    const val EXTRA_TOKEN = "token"
    const val EXTRA_CONFIG_PRESENT = "config_present"
    const val EXTRA_CONFIG_MANUAL_CAPACITY = "config_manual_capacity"
    const val EXTRA_CONFIG_RETENTION_MS = "config_retention_ms"
    const val EXTRA_CONFIG_IGNORE_PACKAGE_LIMIT = "config_ignore_package_limit"
    const val EXTRA_CONFIG_SYNC_ENABLED = "config_sync_enabled"
    const val EXTRA_CONFIG_DEBUG_LOGGING = "config_debug_logging"
    const val EXTRA_CONFIG_SOURCE = "config_source"
    const val EXTRA_MODULE_VERSION = "module_version"
    const val EXTRA_GBOARD_VERSION_NAME = "gboard_version_name"
    const val EXTRA_GBOARD_VERSION_CODE = "gboard_version_code"
    const val EXTRA_GBOARD_PACKAGE = "gboard_package"
    const val EXTRA_PROCESS_NAME = "process_name"
    const val EXTRA_SYNC_ENABLED = "sync_enabled"
    const val EXTRA_CONFIGURED_CAPACITY = "configured_capacity"
    const val EXTRA_EFFECTIVE_CAPACITY = "effective_capacity"
    const val EXTRA_RETENTION_MS = "retention_ms"
    const val EXTRA_DEBUG_LOGGING = "debug_logging"
    const val EXTRA_PRIMARY_CLASS_PRESENT = "primary_class_present"
    const val EXTRA_WATCHERS = "watchers"
    const val EXTRA_OBSERVED_PATHS = "observed_paths"
    const val EXTRA_REWRITE_PROOF = "rewrite_proof"
    const val EXTRA_LAST_ERROR = "last_error"
    const val EXTRA_TIMESTAMP_MS = "timestamp_ms"
}
